# Install Nginx Service on Ubuntu
# Start the Service and Enable it
# Check the status of Nginx
- name: Setup Nginx server on myserver list
  hosts: myservers
  become: True
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install the latest version of nginx
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Enable nginx
      ansible.builtin.service:
        name: nginx
        enabled: yes

    - name: Ensure nginx is at the latest version
      ansible.builtin.command: nginx -v

    - name: Get status of nginx installed
      ansible.builtin.command: systemctl status nginx
